---
title: "Untitled"
author: "Tie Ma"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#Note: this file include the processing of downloding the Data from the IMS and cleaning process 
#wrote by Tie at 2024/05/18

#note: its does not
#note: just downlode it and run this code to cleaning
```

```{R}
#update history
################
#2024/05/24  #0.0.1 create the this marketdown and doing the first round of test data collection. 
#2024/05/25  #0.0.2 further improve the data cleaning 
#2024/05/26  #0.0.3 add the code section of create IMF data check list for better understand and cleaning this data.  
#2024/07/16  #0.0.4 update the code and improve the readability for future reader and myself
#2024/07/16  #0.0.5 improve the code and aline this with USD and remove the code of downlode the data
################

```



```{r setup, include=FALSE}
#this file is for processing the Raw data from entire OECD data set from 1950 - 2023 
#as the Raw code processing file for the RA data job for professor Hassmant
#Tie Ma 2024/05/18

################################################################################

#clean the enviroment
rm(list = ls())

#set the working direction
#for mac
#setwd("/Users/tie/Documents/GitHub/RA-data-clening")

#for windosw
#setwd("D:/github/RA-data-clening/code")



################################################################################
#Step one Lode the all package that necessary. 
#some of them may not be used this file
#I just copy them around, so it will make my life easier 

library (lubridate)     #the time series processing package
library (cansim)        #provides easy access to the statistics canada data tale
library (WDI)           #Accesses data from the world development indicators
library (fredr)         #provide an interface to the federal reserve economic data API
library (tsbox)         #Make time series convverstion, aggregation and plotting simple
library (RColorBrewer)  #color palettes for R graphics
library(wesanderson)    #Provides color palettes inspired by Wes Anderson films.
library(writexl)        #Writes data frames to Excel files.
library(tidyr)          #Tidies messy data   
library(xts)            #Extensible time series class for R   
library(dplyr)          #Data manipulation and transformation.
library(openxlsx)       #Read, write, and edit Excel files.
#library(IMFData)     #accessing the data from the IMF data 
library(readxl)
library(readr)

```

```{R}
#import the data

IFS_gross_GDP <- read_excel("~/Library/CloudStorage/OneDrive-CarletonUniversity/The GDP data cleaning-TIEMA/R code for the country list cleaning/Final data processing code/IFS data set/IFS gross GDP.xlsx")


IFS_real_GDP <- read_excel("~/Library/CloudStorage/OneDrive-CarletonUniversity/The GDP data cleaning-TIEMA/R code for the country list cleaning/Final data processing code/IFS data set/IFS real GDP.xlsx")

```

```{r}

IFS_gross_GDP_long <- IFS_gross_GDP%>%
  pivot_longer(
    cols = -Country,       # All columns except 'Country'
    names_to = "Year",     # New column for year
    values_to = "gross_GDP"      # New column for GDP values
  )


```


```{R}

IFS_real_GDP_long <- IFS_real_GDP %>%
  pivot_longer(
    cols = -Country,       # All columns except 'Country'
    names_to = "Year",     # New column for year
    values_to = "real_GDP"      # New column for GDP values
  )
  

```


```{r}
#put two data set together
IFS_na_raw <- IFS_gross_GDP_long %>% 
  left_join(IFS_real_GDP_long, by = c("Country", "Year"))
```

```{r}
#remove na col 
IFS_na_raw<- IFS_na_raw %>% mutate(across(everything(), ~ na_if(., "...")))

IFS_raw <- na.omit(IFS_na_raw)
 
```

```{R}

#transfer the data into the data
IFS_raw$Year <- as.numeric(IFS_raw$Year)
IFS_raw$gross_GDP <- as.numeric(IFS_raw$gross_GDP)
IFS_raw$real_GDP <- as.numeric(IFS_raw$real_GDP)

```


```{r}

# Calculate Price Levels (P_t)
IFS_raw <- IFS_raw %>%
  group_by(Country) %>%
  mutate(Price_Level = gross_GDP / real_GDP)


```


```{R}
# Calculate Inflation Rates (π_t)
IFS_raw <- IFS_raw %>%
  arrange(Country, Year) %>%
  mutate(Inflation_Rate = ((Price_Level - lag(Price_Level))/ lag(Price_Level))* 100)

# Print the resulting data frame
print(IFS_raw, n = 100)

#remove the na_col 

IFS_raw <- na.omit(IFS_raw)

print(IFS_raw)

```

```{R}
#this line of code is for the mac
write_xlsx(IFS_raw, "/Users/tie/Library/CloudStorage/OneDrive-CarletonUniversity/The GDP data cleaning-TIEMA/R code for the country list cleaning/Final data processing code/IFS data set/IFS_raw.xlsx")



```








```